-- USERPROFILE definition

CREATE TABLE "USERPROFILE"
   ( "USERID" VARCHAR2(40) NOT NULL ENABLE,
	"USERNAME" VARCHAR2(40),
	"USERGROUPNAME" VARCHAR2(80),
	"PASSWORD" VARCHAR2(200),
	"DEPARTMENT" VARCHAR2(40),
	"PHONENUMBER" VARCHAR2(40),
	"EMAIL" VARCHAR2(200),
	"LOCALENAME" VARCHAR2(40),
	"LASTLOGINTIME" DATE,
	"LASTPASSWORDTIME" DATE,
	"VALIDFLAG" VARCHAR2(10),
	"FMBDEFAULTFACTORYNAME" VARCHAR2(40),
	"LASTEVENTCOMMENT" VARCHAR2(250)
   ) ;

;

ALTER TABLE "USERPROFILE" ADD CONSTRAINT "USERPROFILE_PK" PRIMARY KEY ("USERID") ;

;

CREATE TABLE "RMDFACTORY"
   (
   "FACTORYNAME" VARCHAR2(40) NOT NULL ENABLE,
	"DEFAULTFACTORYFLAG" VARCHAR2(40),
	"POSITION" VARCHAR2(40),
   ) ;



ALTER TABLE RMDFACTORY ADD CONSTRAINT "RMDFACTORY_PK" PRIMARY KEY ("FACTORYNAME");

DROP TABLE RMDCOLORSET CASCADE CONSTRAINTS;

CREATE TABLE "RMDCOLORSET"
   (
   "TYPENAME" VARCHAR2(40) NOT NULL ENABLE,
   	"STATENAME" VARCHAR2(40),
   	"STATEVALUE" VARCHAR2(40),
	"TYPEATTRIBUTE" VARCHAR2(40),
	"TYPEATTRIBUTEVALUE" VARCHAR2(40)
   ) ;

ALTER TABLE "RMDCOLORSET" ADD CONSTRAINT "RMDCOLORSET_PK" PRIMARY KEY ("TYPENAME","STATENAME","STATEVALUE","TYPEATTRIBUTE") ;